# Generated by Django 5.2.1 on 2025-05-23 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_post_updated_at_post_image_alter_post_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
