# Generated by Django 5.2.1 on 2025-05-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_like_unique_together_like_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isliked',
            field=models.BooleanField(default=False),
        ),
    ]
