# Generated by Django 5.2.1 on 2025-05-28 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_isliked_post_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_liked',
        ),
    ]
